### ISSUE TITLE
Which is the forecast of the cost for the service?

### ISSUE THREAD

**Issue by alvarofvr** [rileydakota/valheim-ecs-fargate-cdk#2]
How much does the service cost considering the current state of Valheim's dedicated server?

**Comment by alvarofvr** [comment]
Based on AWS pricing for eu-central-1: 


```
0,04656 USD per vCPU per hour
0,00511 USD per GB per hour
```

Considering to mantain active for 24 hours for 30 days each month it's too much!

**Comment by rileydakota** [comment]
Hi @alvarofvr  - FWIW you **may** be able to reduce the cost by reducing the CPU and Memory allocated here:  https://github.com/rileydakota/valheim-ecs-fargate-cdk/blob/main/lib/valheim-server-aws-cdk-stack.ts#L56 (I make no promise to the memory usage staying stable)

I regularly have 5-6 people playing on my server and Memory usage seems to be a stable ~42%, with CPU usage not even approaching that:

![image](https://user-images.githubusercontent.com/73837129/108531622-e3623800-72a4-11eb-9afd-3e46c422a360.png)
(The spike is when my friend group is connected)

You will probably save money with EC2 or standard ECS - but I tend to opt for managed services as they are highly relevant to my professional work, I don't like managing servers, and AWS has only decreased the pricing of Fargate to date. 

Could also consider scheduling the ECS Task to only run at particular times based on your common play hours: https://aws.amazon.com/about-aws/whats-new/2018/08/aws-fargate-now-supports-time-and-event-based-task-scheduling/

Good luck!
