### ISSUE TITLE
Assistance: Modifying Environment after already starting up the server

### ISSUE THREAD

**Issue by samuelzapote** [rileydakota/valheim-ecs-fargate-cdk#21]
Hello Team, big thanks to all the work you do! I really appreciate it.
I was hoping to get some assistance or documentation on some doubts i'm having.

I am trying to add the environment variable event hooks documented [here](https://hub.docker.com/r/lloesche/valheim-server#event-hooks) on docker hub. But I believe in order to do so I need to modify the docker environment variables. 

I was wondering if anyone could help me by pointing me in the right direction or with some documentation I can read up on to accomplish the following. 

1. I want to be able to stop the docker container without losing my game files / saved world.
2. My understanding is that once I stop the container, I can then go in to "modify" the docker environment variables. I read on another issue posted that I can access the ECS files / docker container using [AWS Transfer Family](https://github.com/rileydakota/valheim-ecs-fargate-cdk/issues/12#issuecomment-787520503) . I can handle that part, but will accessing this file system allow me to modify the docker file, and will I be able to ensure that I modify those files while the task/docker container is stopped? 

Big thanks for any help in advance. 😄 spectacular work on this project!

**Comment by rileydakota** [comment]
Hi @samuelzapote - thanks for using the template! You can add new environment variables by modifying the code here: https://github.com/rileydakota/valheim-ecs-fargate-cdk/blob/876180c3e6ff6dc39e0cf58558e707ea5ef6275c/lib/valheim-server-aws-cdk-stack.ts#L68

If you only change the environment variables - you shouldn't experience any loss of game files/world - as the server save file is saved on the EFS volume. In addition to this  - the EFS volume has a deletion policy on it so it will not be lost in the event you decide to delete the cloudformation stack. You shouldn't need to modify anything on the container itself to accomplish this. Let me know if you run into issues!

**Comment by samuelzapote** [comment]
This really helped! Thank You. Closing this issue given that it's been resolved.
