### ISSUE TITLE
Having issue to start Fargate - Stuck on 19/21

### ISSUE THREAD

**Issue by Batuu13** [rileydakota/valheim-ecs-fargate-cdk#9]
First of all thanks for making this!

I think I followed the guide thoroughly but I am having this error when ever a task is being started on my fargate

`ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secret from asm: service call has been retried 1 time(s): invalid character '\'' looking for beginning of value`

I check every where but I am not sure where this '\' character coming from?

thank you verch much for the help!

**Comment by sdredsoxfan** [comment]
My only guess is that there's something wrong with the secret. I assume you ran the below command to create your secret?

```
aws secretsmanager create-secret --name valheimServerPass --secret-string '{"VALHEIM_SERVER_PASS":"SuperSecretServerPassword"}'
```

Also you don't need the secret at all if you'd like. You can remove the following lines (apologies for the multiple links, but not sure how to select these lines independently)

[L4](https://github.com/rileydakota/valheim-ecs-fargate-cdk/blob/main/lib/valheim-server-aws-cdk-stack.ts#L4)
[L13-18](https://github.com/rileydakota/valheim-ecs-fargate-cdk/blob/main/lib/valheim-server-aws-cdk-stack.ts#L13-L18)
[L86-91](https://github.com/rileydakota/valheim-ecs-fargate-cdk/blob/main/lib/valheim-server-aws-cdk-stack.ts#L86-L91)

Then just hard code the SERVER_PASS in the environment variable for your Valheim container like so:

```
environment: {
        SERVER_NAME: "VALHEIM-SERVER-AWS-ECS",
        SERVER_PORT: "2456",
        SERVER_PASS: "MySuperSecurePassword",
        WORLD_NAME: "VALHEIM-WORLD-FILE",
        ...
```

This might just bypass your issue.

**Comment by rileydakota** [comment]
@sdredsoxfan thanks for commenting back - your workaround is absolutely correct! Important to be aware that sharing your code will also share your password in this case (which may or may not matter to you if you are the only one with access to the code). @Batuu13 would be interested in the details of how you created your secret (Name, Resource Policy, JSON structure of value) so we can triage this and add it to the docs

**Comment by sdredsoxfan** [comment]
@rileydakota Oh I'm not using any real pw information here and it's a good callout that if someone does go this route, publishing changes to your own github repository or something similar does make this information public

**Comment by Batuu13** [comment]
Hey guys, I guess I wrote the secret without " or something went wrong so I edited the secret manually to make it an object then it worked perfectly!
